/* swigconfig.h. Generated by cmake from Tools/cmake/swigconfig.h.in */

/* define if the Boost library is available */
/* #undef HAVE_BOOST */

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the `dl' library (-ldl). */
/* #undef HAVE_LIBDL */

/* Define to 1 if you have the `dld' library (-ldld). */
/* #undef HAVE_LIBDLD */

/* Define if you have PCRE library */
#define HAVE_PCRE 1

/* Define if popen is available */
/* #undef HAVE_POPEN */

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdio.h> header file. */
#define HAVE_STDIO_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
/* #undef HAVE_STRINGS_H */

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
/* #undef HAVE_UNISTD_H */

/* Name of package */
#define PACKAGE "swig"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "https://www.swig.org"

/* Define to the full name of this package. */
#define PACKAGE_NAME "swig"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "swig 4.4.0"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "swig"

/* Define to the home page for this package. */
#define PACKAGE_URL ""

/* Define to the version of this package. */
#define PACKAGE_VERSION "4.4.0"

/* The size of `void *', as computed by sizeof. */
/* #undef SIZEOF_VOID_P */

/* Define to 1 if all of the C90 standard headers exist (not just the ones
   required in a freestanding environment). This macro is provided for
   backward compatibility; new code need not use it. */
#define STDC_HEADERS 1

/* Compiler that built SWIG */
#define SWIG_CXX "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe"

/* Directory for SWIG system-independent libraries */
#define SWIG_LIB "D:/Code/swig/swig/../out/install/x64-Debug/bin/Lib"

/* Directory for SWIG system-independent libraries (Unix install on native
   Windows) */
#define SWIG_LIB_WIN_UNIX ""

/* Platform that SWIG is built for */
#define SWIG_PLATFORM "Windows"

/* Version number of package */
#define VERSION "4.4.0"


/* Deal with attempt by Microsoft to deprecate C standard runtime functions */
#if defined(_MSC_VER)
# define _CRT_SECURE_NO_DEPRECATE
#endif

